### ISSUE TITLE
Blocked Sites

### ISSUE THREAD

**Issue by Ahmad-2213** [6Kmfi6HP/EDtunnel#31]
There's an issue with some Sites that they block cloudflare IPs even if they're not using cloudlfare's CDNs .
Is there any ways to force these kind of sites going through Proxyip?
I'd suppose you're already aware of Twitch.tv Source quality issue , there are many more websites that are unable to be reached using cloudflare IPs.
So please add an option to redirect these sites through proxyIP.
Thank you !

**Comment by 6Kmfi6HP** [comment]
proxyIP only accept website using Cloudflare's CDN.

**Comment by Ahmad-2213** [comment]
so there is no soloution to this problem?
I've got one more unrelated question which is about the Socks5 Project you've forked.
I tried it and gave me better ping time compared to vless Edge tunnel.
big problem is the dns is resolved directly which causes the Firewall to block the request.
will you consider an update to fix the issue? , if so, will it become compatible with v2ray client?

**Comment by 6Kmfi6HP** [comment]
Set the SOCKS5 variable SOCKS5_RELAY set to true and all traffic will through the socks5 server

**Comment by Ahmad-2213** [comment]
is there any ways to add udp to code, does cloudflare now supports udp and mux?

**Comment by 6Kmfi6HP** [comment]
vless or socks5 as outbound will support udp
