### ISSUE TITLE
About Drivepage and store

### ISSUE THREAD

**Issue by FrenTim** [6Kmfi6HP/EDtunnel#36]
Hi there. I've noticed there is a drivepage when the project uploaded to cf pages. So, is there any ways to edit the files that uploaded to the driver? I'm wondering because there is no button to edit or even remove the files uploaded to it. 
Could you please give some ideas about it. Sincerely thank you for your help.

**Comment by 6Kmfi6HP** [comment]
Cannot delete or edit. the file list is stored in the browser, but u cannot delete files in ipfs.
The best way to clear ur file list is to delete the website's cookies.

**Comment by FrenTim** [comment]
I understand it now. So, the files were uploaded to ipfs. I am reading the document of ipfs to gain more informations. Thank you for answering me, I'm going to seek more about all these intresting projects. Wish you have a relaxing day/time. ^_^
