### ISSUE TITLE
怀疑DNS配置有问题导致连不上,在v2rayng上实测只有通过启用本地DNS后可以正常使用

### ISSUE THREAD

**Issue by xxntmctx** [6Kmfi6HP/EDtunnel#47]
下面这里是debug日志，求大佬看看
--------- beginning of main
12-02 11:14:59.756 I/GoLog   (18562): [Info] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://caixukun.com:2086/xe9myqi3nn): 301 Moved Permanently > websocket: bad handshake
12-02 11:14:59.756 I/GoLog   (18562): [Debug] app/log: Logger closing
12-02 11:14:59.756 D/com.v2ray.ang(18562): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
12-02 11:14:59.778 I/GoLog   (18562): fdConn unix.Connect err, Close Fd: 119 Err: connection timed out
12-02 11:14:59.864 I/GoLog   (18562): [Info] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://caixukun.com:2095/xe9myqi3nn): 301 Moved Permanently > websocket: bad handshake
12-02 11:14:59.864 I/GoLog   (18562): [Debug] app/log: Logger closing
12-02 11:14:59.865 D/com.v2ray.ang(18562): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
12-02 11:14:59.905 I/GoLog   (18562): [Debug] app/log: Logger closing
12-02 11:14:59.905 D/com.v2ray.ang(18562): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
12-02 11:14:59.917 I/GoLog   (18562): [Info] [2538121611] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
12-02 11:15:00.035 I/GoLog   (18562): fdConn unix.Connect err, Close Fd: 131 Err: connection timed out
12-02 11:15:00.079 I/GoLog   (18562): Not Using Prepared: tcp,cdn.xn--b6gac.eu.org:443
12-02 11:15:00.081 I/GoLog   (18562): [Info] transport/internet/tcp: dialing TCP to tcp:cdn.xn--b6gac.eu.org:443
12-02 11:15:00.111 I/GoLog   (18562): [Info] [4130861101] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
12-02 11:15:00.217 I/GoLog   (18562): Not Using Prepared: tcp,caixukun.com:2095
12-02 11:15:00.217 I/GoLog   (18562): [Debug] app/log: Logger started
12-02 11:15:00.226 I/GoLog   (18562): [Warning] core: Xray 24.10.16 started
12-02 11:15:00.226 I/GoLog   (18562): [Info] app/dispatcher: default route for tcp:www.gstatic.com:443
12-02 11:15:00.226 I/GoLog   (18562): [Info] transport/internet/websocket: creating connection to tcp:caixukun.com:2095
12-02 11:15:00.226 I/GoLog   (18562): [Info] proxy/vless/outbound: tunneling request to tcp:www.gstatic.com:443 via caixukun.com:2095
12-02 11:15:00.238 I/GoLog   (18562): Not Using Prepared: tcp,cdn.xn--b6gac.eu.org:443
12-02 11:15:00.242 I/GoLog   (18562): [Info] [1364208054] proxy/socks: TCP Connect request to tcp:103.235.47.196:8000
12-02 11:15:00.242 I/GoLog   (18562): [Info] transport/internet/tcp: dialing TCP to tcp:cdn.xn--b6gac.eu.org:443
12-02 11:15:00.357 I/GoLog   (18562): [Info] [1364208054] app/dispatcher: taking detour [proxy] for [tcp:103.235.47.196:8000]
12-02 11:15:00.357 I/GoLog   (18562): [Info] [1364208054] transport/internet/websocket: creating connection to tcp:caixukun.com:443
12-02 11:15:00.357 I/GoLog   (18562): [Info] [1364208054] proxy/vless/outbound: tunneling request to tcp:103.235.47.196:8000 via caixukun.com:443
12-02 11:15:00.357 I/GoLog   (18562): from tcp:127.0.0.1:45252 accepted tcp:103.235.47.196:8000 [socks -> proxy]
12-02 11:15:00.358 I/GoLog   (18562): [Info] [1364208054] transport/internet: redirecting request tcp:caixukun.com:443 to fragment
12-02 11:15:00.547 I/GoLog   (18562): fdConn unix.Connect err, Close Fd: 115 Err: connection timed out
12-02 11:15:00.570 I/GoLog   (18562): Using Prepared: 172.67.202.44
12-02 11:15:00.771 D/com.v2ray.ang(18562): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
12-02 11:15:00.771 I/GoLog   (18562): [Info] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://caixukun.com:2095/xe9myqi3nn): 301 Moved Permanently > websocket: bad handshake
12-02 11:15:00.771 I/GoLog   (18562): [Debug] app/log: Logger closing
12-02 11:15:00.802 I/GoLog   (18562): fdConn unix.Connect err, Close Fd: 127 Err: connection timed out
12-02 11:15:00.828 I/GoLog   (18562): [Debug] app/log: Logger started
12-02 11:15:00.829 I/GoLog   (18562): [Warning] core: Xray 24.10.16 started
12-02 11:15:00.829 I/GoLog   (18562): [Info] app/dispatcher: default route for tcp:www.gstatic.com:443
12-02 11:15:00.829 I/GoLog   (1856

**Comment by iicemeta** [comment]
我的v2rayNG除了tg都无法使用，Google play和copilot都打不开

**Comment by xxntmctx** [comment]
@6Kmfi6HP 你好，我多次测试发现好像确实是DNS问题，默认的v2rayng启用的是1.1.1.1DNS会有冲突，只要在设置里面把VPN DNS改成其他的DNS例如8.8.8.8就全部正常了

**Comment by iicemeta** [comment]
@xxntmctx 我也改了8.8.8.8的DNS，但是没有用，只能打开tg，GitHub和Google play，copilot都打不开

**Comment by xxntmctx** [comment]
> @xxntmctx 我也改了8.8.8.8的DNS，但是没有用，只能打开tg，GitHub和Google play，copilot都打不开

设置里启用本地DNS和虚拟DNS
