### ISSUE TITLE
Some default proxyip in proxyIPs dead, can setup a new environment variable for setting the default proxyIPs

### ISSUE THREAD

**Issue by mickey3721** [6Kmfi6HP/EDtunnel#58]
![image](https://github.com/user-attachments/assets/54b7cb2d-c521-47e1-adfc-6c74e928dcd5)

Some default proxyip in proxyIPs dead, can setup a new environment variable for setting the default proxyIPs

**Comment by 6Kmfi6HP** [comment]
set PROXYIP will auto add ips to subscribe content.
