### ISSUE TITLE
1101错误如何处理

### ISSUE THREAD

**Issue by byteappua** [6Kmfi6HP/EDtunnel#77]

**Comment by Alex-0627** [comment]
Occurred same question

**Comment by cclrc-01** [comment]
我也是出现1101

**Comment by GrowingHacker** [comment]
哈哈哈，一看都是小白用户，最简单的方法：删了重建，要用最新的文件

**Comment by cclrc-01** [comment]
真的吗？我试试看，不对啊，它的文件很长时间没有更新了，那个BPB面板也是101错误，我删了重建几次了，都没有用，还是101错误

**Comment by 6Kmfi6HP** [comment]
https://cfworker.edtunnel.best/

**Comment by cclrc-01** [comment]
Ok, thanks for letting me know.
